apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-load-balancer-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: global-load-balancer-operator
  template:
    metadata:
      labels:
        name: global-load-balancer-operator
    spec:
      serviceAccountName: global-load-balancer-operator
      containers:
        - name: global-load-balancer-operator
          # Replace this with the built image name
          image: quay.io/redhat-cop/global-load-balancer-operator:{{ .Values.image_tag }}
          command:
          - global-load-balancer-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "global-load-balancer-operator"
                            
